In [1]:
import numpy as np 
import pandas as pd
import sys
import matplotlib.pyplot as plt
from datetime import datetime
import seaborn as sns

In [2]:
ACC_66=pd.read_csv('1571129566_A013E1\ACC.csv')
BVP_66=pd.read_csv('1571129566_A013E1\BVP.csv') ##Blood Volume Pulse
EDA_66=pd.read_csv('1571129566_A013E1\EDA.csv')
HR_66=pd.read_csv('1571129566_A013E1\HR.csv')
IBI_66=pd.read_csv('1571129566_A013E1\IBI.csv') #inter-beat-interval
ACC_61=pd.read_csv('1571132161_A013E1\ACC.csv')
BVP_61=pd.read_csv('1571132161_A013E1\BVP.csv') ##Blood Volume Pulse
EDA_61=pd.read_csv('1571132161_A013E1\EDA.csv')
HR_61=pd.read_csv('1571132161_A013E1\HR.csv')
IBI_61=pd.read_csv('1571132161_A013E1\IBI.csv') #inter-beat-interval

In [4]:
print('ACC_66 : ',len(ACC_66))
print('BVP_66 : ',len(BVP_66))
print('EDA_66 : ',len(EDA_66))
print('HR_66 : ',len(HR_66))
print('IBI_66 : ',len(IBI_66))
print("------------------------")
print('ACC_61 : ',len(ACC_61))
print('BVP_61 : ',len(BVP_61))
print('EDA_61 : ',len(EDA_61))
print('HR_61 : ',len(HR_61))
print('IBI_61 : ',len(IBI_61))

ACC_66 :  79279
BVP_66 :  158555
EDA_66 :  9907
HR_66 :  2469
IBI_66 :  780
------------------------
ACC_61 :  28801
BVP_61 :  57597
EDA_61 :  3601
HR_61 :  891
IBI_61 :  450

In [5]:
ACC_29=pd.read_csv('1571133129_A013E1\ACC.csv')
BVP_29=pd.read_csv('1571133129_A013E1\BVP.csv') ##Blood Volume Pulse
EDA_29=pd.read_csv('1571133129_A013E1\EDA.csv')
HR_29=pd.read_csv('1571133129_A013E1\HR.csv')
IBI_29=pd.read_csv('1571133129_A013E1\IBI.csv') #inter-beat-interval

In [6]:
print('ACC_29 : ',len(ACC_29))
print('BVP_29 : ',len(BVP_29))
print('EDA_29 : ',len(EDA_29))
print('HR_29 : ',len(HR_29))
print('IBI_29 : ',len(IBI_29))

ACC_29 :  98017
BVP_29 :  196032
EDA_29 :  12253
HR_29 :  3054
IBI_29 :  2408

In [7]:
#위를 통해서 ACC : BVP : EDA : HR  = 2 : 1 : 16 : 64의 비를 찾을 수 있었고 이를 이용해서 데이터를 합친다
a=len(ACC_29)/32
b=len(BVP_29)/64
c=len(EDA_29)/4
d=len(HR_29)
print(a,b,c,d)

3063.03125 3063.0 3063.25 3054

In [99]:
a=BVP_29.loc[::64]
b=ACC_29.loc[::32]
c=EDA_29.loc[::4]

In [107]:
a=a.reset_index()
b=b.reset_index()
c=c.reset_index()

In [110]:
DataSet=pd.DataFrame(columns=['BVP','ACC','EDA','HR'])
DataSet['BVP'] = a.iloc[:,1]
DataSet['ACC'] = b.iloc[:,1]
DataSet['EDA'] = c.iloc[:,1]
DataSet['HR']=HR_29

In [112]:
DataSet=DataSet.drop(DataSet.index[len(HR_29):len(DataSet)])

In [113]:
DataSet

         BVP   ACC       EDA      HR
0          0  32.0  4.000000    1.00
1         64  17.0  0.148599   52.00
2        128  17.0  0.148599   67.50
3        192  17.0  0.151161   70.33
4        256  17.0  0.149880   78.75
5        320  28.0  0.152442   86.80
6        384   8.0  0.148599   89.67
7        448  19.0  0.149880   91.57
8        512  18.0  0.146037   93.25
9        576  16.0  0.148599   94.67
10       640  13.0  0.146037   95.60
11       704  27.0  0.144756   96.18
12       768  57.0  0.147318   96.83
13       832 -49.0  0.143475   97.38
14       896   0.0  0.146037   97.00
15       960  31.0  0.144756   96.80
16      1024  22.0  0.155004   96.62
17      1088  52.0  0.158847   96.35
18      1152  62.0  0.156285   96.06
19      1216  25.0  0.153723   95.84
20      1280  10.0  0.152442   95.10
21      1344  19.0  0.156285   94.38
22      1408  52.0  0.153723   93.64
23      1472  39.0  0.155004   92.91
24      1536   2.0  0.148599   92.25
25      1600   4.0  0.148599   91.80
26      1664  16.0  0.144756   91.12
27      1728  20.0  0.151161   90.48
28      1792  21.0  0.149880   90.00
29      1856  20.0  0.146037   89.66
...      ...   ...       ...     ...
3024  193536  46.0  0.438110  104.87
3025  193600  48.0  0.438110  104.85
3026  193664  51.0  0.435548  104.80
3027  193728  52.0  0.436829  104.68
3028  193792  47.0  0.435548  104.57
3029  193856  53.0  0.434267  104.50
3030  193920  47.0  0.435548  104.40
3031  193984  56.0  0.432986  104.27
3032  194048  52.0  0.454763  104.15
3033  194112  60.0  0.439391  104.13
3034  194176  53.0  0.458606  104.08
3035  194240  31.0  0.463730  104.03
3036  194304   7.0  0.453482  103.95
3037  194368  32.0  0.466292  103.87
3038  194432  69.0  0.482946  103.78
3039  194496  44.0  0.491913  103.70
3040  194560  43.0  0.525219  103.78
3041  194624  56.0  0.531624  103.92
3042  194688  54.0  0.530343  104.07
3043  194752  48.0  0.632825  104.33
3044  194816  32.0  0.631544  104.53
3045  194880  28.0  0.602081  104.73
3046  194944  37.0  0.622577  104.93
3047  195008  41.0  0.634106  105.13
3048  195072  30.0  0.594394  105.33
3049  195136  84.0  0.598238  105.52
3050  195200  82.0  0.576460  105.70
3051  195264  64.0  0.609767  105.88
3052  195328  64.0  0.605924  106.03
3053  195392  62.0  0.607205  106.15

[3054 rows x 4 columns]

In [114]:
len(DataSet)/3

1018.0

In [22]:
BVP.append(BVP_29.loc[4])
BVP.append(BVP_29.loc[8])
BVP.append(BVP_29.loc[12])

In [23]:
BVP

[1571133129.00   -0.0
 Name: 4, dtype: float64, 1571133129.00   -0.0
 Name: 4, dtype: float64, 1571133129.00   -0.0
 Name: 8, dtype: float64, 1571133129.00    0.01
 Name: 12, dtype: float64]

In [9]:
for i in range(len(BVP_29)):
    if i%4=0:
        BVP.append()

        1571133129.00
0               64.00
1               -0.00
2               -0.00
3               -0.00
4               -0.00
5               -0.00
6               -0.00
7               -0.00
8               -0.00
9               -0.00
10              -0.00
11               0.00
12               0.01
13               0.01
14              -0.00
15              -0.03
16              -0.05
17              -0.05
18               0.00
19               0.13
20               0.36
21               0.66
22               1.01
23               1.37
24               1.72
25               2.06
26               2.40
27               2.79
28               3.24
29               3.80
...               ...
196002          -6.20
196003         -12.69
196004         -20.31
196005         -29.39
196006         -39.92
196007         -51.42
196008         -62.88
196009         -72.92
196010         -79.97
196011         -82.68
196012         -80.38
196013         -73.21
196014         -62.17
196015         -48.70
196016         -34.29
196017         -20.10
196018          -6.89
196019           4.96
196020          15.20
196021          23.63
196022          30.12
196023          34.71
196024          37.64
196025          39.41
196026          40.55
196027          41.52
196028          42.56
196029          43.74
196030          44.96
196031          46.12

[196032 rows x 1 columns]